package as_Parser;

import java.util.ArrayList;
import java.util.List;

//#############################################
//## file: Parser.java
//## Generated by Byacc/j
//#############################################
/**
 * BYACC/J Semantic Value for parser: Parser
 * This class provides some of the functionality
 * of the yacc/C 'union' directive
 */
public class ParserVal 
{
/**
 * integer value of this 'union'
 */
public int ival;

/**
 * double value of this 'union'
 */
public double dval;

/**
 * string value of this 'union'
 */
public String sval =new String();

public int kind = 0;

public int row = 0;

public String  type;
/**
 * object value of this 'union'
 */
public List<ParserVal> list = new ArrayList<ParserVal>();

public Object obj;

//#############################################
//## C O N S T R U C T O R S
//#############################################
/**
 * Initialize me without a value
 */
public ParserVal()
{
}
/**
 * Initialize me as an int
 */
public ParserVal(int val)
{
  ival=val;
}

/**
 * Initialize me as a double
 */
public ParserVal(double val)
{
  dval=val;
}

/**
 * Initialize me as a string
 */
public ParserVal(String val)
{
  sval=val;

}



public ParserVal Clone(){
	ParserVal np = new ParserVal();
	np.sval = this.sval;
	np.kind = this.kind;
	np.row = this.row;
	return np;
	
}

	public void addToList(ParserVal n){
		list.add(n);
	}

}//end class

//#############################################
//## E N D    O F    F I L E
//#############################################
